### ISSUE TITLE
Add a property to quality attributes to indicate if it is a NFR or FR, by default I suggest treating them as NFR (this is not backwards compatible but IMO it makes more sense)

### ISSUE THREAD

**Issue by Rezenders** [meta-control/mc_mdl_tomasys#10]
Add a property to quality attributes to indicate if it is a NFR or FR, by default I suggest treating them as NFR (this is not backwards compatible but IMO it makes more sense)
Related to: https://github.com/meta-control/mc_mros_reasoner/issues/141

**Comment by Rezenders** [comment]
Done at: 7eba2b2b91d884bb144e7c051ec682c94ca4f241

**Comment by Rezenders** [comment]
FYI @chcorbato

**Comment by chcorbato** [comment]
This needs to be analyzed in detail considering engineering practices and terminology, and analyzed from a modeling perspective in your KB papers 😊
